spring.application.name=qrpass-hub-api
server.servlet.context-path=/api/v1

# Server
spring.datasource.url=jdbc:postgresql://localhost:5432/qrpass_hub
spring.datasource.username=qrpass_hub
spring.datasource.password=qrpass_hub
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-test.sql
